### ISSUE TITLE
Help: Can't install LOS: ADB sideload error (TWRP): Process updater ended with ERROR: 7

### ISSUE THREAD

**Issue by realpixelcode** [LineageOS/android_device_samsung_gts4lv-common#3]
Hi, please help me with my problem. I've followed [this LOS installation instruction](https://wiki.lineageos.org/devices/gts4lvwifi/install) and I'm now inside TWRP trying to ADB-sideload LineageOS.

But it doesn't work – I got the following error:

```ERROR: This package requires firmware from an Android 10 based stock ROM build. Please upgrade firmware and retry! Process updater ended with ERROR: 7```

I don't want to turn off the device because I get the warning "No OS installed! Are you sure you want to turn off?"

Please help me! What should I do now?

Thank you!

**Comment by luk1337** [comment]
Error message seems pretty clear. Reflash latest stock rom and start over.

**Comment by realpixelcode** [comment]
How do I do that? Where do I get the latest stock ROM from?

**Comment by luk1337** [comment]
The same way you'd do it for 1000 other samsung devices, you'll find the guides on google.

**Comment by realpixelcode** [comment]
Sorry, I've never done that before. Isn't it a problem that TWRP tells me I've no OS installed?

**Comment by luk1337** [comment]
Not really, the mode used to flash firmware etc is still present.

**Comment by realpixelcode** [comment]
I've read your post on XDA: https://forum.xda-developers.com/t/rom-official-gts4lvwifi-10-lineageos-17-1.3972371/post-83341191

How do I flash [this](https://github.com/luk1337/gts4lv-fw/releases/tag/T720XXU1CTK1) firmware update? By ADB sideload too?

I'm sorry for bothering you, I'm just new to this all and bit panicking I might do something terribly wrong 😕

**Comment by luk1337** [comment]
It says it's an 'Odin' package thus one would think it has to be flashed in odin...

**Comment by realpixelcode** [comment]
Do I need to go into download mode to do so? Thanks

**Comment by luk1337** [comment]
Does Odin detect your device otherwise?

**Comment by realpixelcode** [comment]
I installed the package now as well as Lineage and everything works now 👍

I would like to thank you very much for helping me and for being involved in Lineage in the first place. I really appreciate your efforts - thank you so much ❤️
